server:
  port: 8761
spring:
  application:
    name: eureka-naming-server
eureka:
  instance:
    hostname: localhost
    preferIpAddress: true
#  client:
#    register-with-eureka: true
#    fetch-registry: false
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/



