server:
  port: 8000
spring:
  application:
    name: roles-service
  cloud:
    config:
      uri: http://localhost:8888
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ddnshop_roles
    username: root
    password: 123456
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
