server:
  port: 8100
spring:
  application:
    name: users-service
  profiles:
    active: dev
  zipkin:
    base-url: http://localhost9411
  cloud:
    config:
      uri: http://localhost:8888
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ddnshop_user
    username: root
    password: 123456
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: false




